//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rental.Core.Resources.AuthMessages", typeof(AuthMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token has expired..
        /// </summary>
        public static string Refresh_Token_Expired {
            get {
                return ResourceManager.GetString("Refresh_Token_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token generated successfully..
        /// </summary>
        public static string Refresh_Token_Generated_Successfully {
            get {
                return ResourceManager.GetString("Refresh_Token_Generated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string Refresh_Token_Invalid {
            get {
                return ResourceManager.GetString("Refresh_Token_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked due to invalid login attempts..
        /// </summary>
        public static string User_Blocked_Invalid_Attempts {
            get {
                return ResourceManager.GetString("User_Blocked_Invalid_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        public static string User_Created_Successfully {
            get {
                return ResourceManager.GetString("User_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot log in without a confirmed email..
        /// </summary>
        public static string User_Email_Not_Confirmed {
            get {
                return ResourceManager.GetString("User_Email_Not_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully logged in..
        /// </summary>
        public static string User_Login_Success {
            get {
                return ResourceManager.GetString("User_Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string User_Or_Password_Incorrect {
            get {
                return ResourceManager.GetString("User_Or_Password_Incorrect", resourceCulture);
            }
        }
    }
}
