//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HealthCheckMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HealthCheckMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rental.Core.Resources.HealthCheckMessages", typeof(HealthCheckMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API itself is running and reachable..
        /// </summary>
        public static string Service_ApiOk {
            get {
                return ResourceManager.GetString("Service_ApiOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is healthy..
        /// </summary>
        public static string Service_Healthy {
            get {
                return ResourceManager.GetString("Service_Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinIO storage service is unavailable. Check the container or port {0}..
        /// </summary>
        public static string Service_MinIODown {
            get {
                return ResourceManager.GetString("Service_MinIODown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL database is unavailable. Check if the container is running on port {0}..
        /// </summary>
        public static string Service_PostgresDown {
            get {
                return ResourceManager.GetString("Service_PostgresDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ message broker is unavailable. Verify the container or port {0}..
        /// </summary>
        public static string Service_RabbitDown {
            get {
                return ResourceManager.GetString("Service_RabbitDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redis cache is unavailable. Make sure the container &apos;{0}&apos; is running on {1}:{2}..
        /// </summary>
        public static string Service_RedisDown {
            get {
                return ResourceManager.GetString("Service_RedisDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All systems operational..
        /// </summary>
        public static string Status_AllOperational {
            get {
                return ResourceManager.GetString("Status_AllOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some services are slow or partially unavailable..
        /// </summary>
        public static string Status_PartiallyUnavailable {
            get {
                return ResourceManager.GetString("Status_PartiallyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more services are unavailable..
        /// </summary>
        public static string Status_Unavailable {
            get {
                return ResourceManager.GetString("Status_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown system status..
        /// </summary>
        public static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }
    }
}
